version: "3"

services:

## -------------------
## Go - Gin Gonic
## -------------------

  be_gin:
    image: "weweb/be/gin"
    build: ./backend/Go-GinGonic
    ports:
      - 8090:8080
    environment:
      SERVER_RESOURCES_STATIC_PATH: ./frontend

## -------------------
## Vertx3 - Angular 
## -------------------

  fe_vertx_angular:
    image: "weweb/fe/angular"
    build:
      context: ./frontend/Angular-Typescript/
      dockerfile: Dockerfile_caddy
    ports:
      - "8091:80"
    depends_on:
      - be_vertx
    environment:
      BACKEND_URL: http://be_vertx:8080
      
  be_vertx:
    image: "weweb/be/vertx"
    build: ./backend/Vertx3-Kotlin

## ----------------------
## SpringBoot2 - Angular
## ----------------------

  fe_springboot_angular:
    image: "weweb/fe/angular"
    build:
      context: ./frontend/Angular-Typescript/
      dockerfile: Dockerfile_nginx
    ports:
      - "8092:80"
    # init: true
    depends_on:
      - be_springboot
    environment:
      BACKEND_URL: http://be_springboot:8080

  be_springboot:
    image: "weweb/be/springboot"
    build: ./backend/SpringBoot2-Java
