version: "3"

services:

## -------------------
## Go - Chi
## -------------------

  go_chi:
    image: "weweb/be/go_chi"
    build: ./backend/Go-Chi
    ports:
      - 8090:8080
    environment:
      SERVER_RESOURCES_STATIC_PATH: ./frontend

      
## -------------------
## Rust - Actix
## -------------------

  rust_actix:
    image: "weweb/be/rust_actix"
    build: ./backend/Rust-Actix
    ports:
      - 8091:8080


## -------------------
## Kotlin - Vertx3 - Angular 
## -------------------

  fe_vertx_angular:
    image: "weweb/fe/angular"
    build: ./frontend/Angular-Typescript
    ports:
      - "8092:80"
    depends_on:
      - be_vertx
    environment:
      BACKEND_URL: http://be_vertx:8080
      NGINX_WORKER_PROCESSES: 1
      #NGINX_WORKER_CONNECTIONS: 16384
      
  be_vertx:
    image: "weweb/be/kolin_vertx"
    build: ./backend/Vertx3-Kotlin

    
## ----------------------
## Java - SpringBoot2 - Angular
## ----------------------

  fe_springboot_angular:
    image: "weweb/fe/angular"
    ports:
      - "8093:80"
    # init: true
    depends_on:
      - be_springboot
    environment:
      BACKEND_URL: http://be_springboot:8080
      NGINX_WORKER_PROCESSES: 1
      #NGINX_WORKER_CONNECTIONS: 16384

  be_springboot:
    image: "weweb/be/java_springboot"
    build: ./backend/SpringBoot2-Java
