[core.logger]
root_level = "warn"
level = "info"
output_system_enabled = true
output_file_enabled = false
output_file_name = "./target/output.log"

[core.server]
port = 8080

[core.jwt]
secret = "mySecret"
signatureAlgorithm = "HS512"
tokenValidityMinutes = 20
