[logger]
root_level = "warn"
level = "info"
output_system_enabled = true
output_file_enabled = false
output_file_name = "./target/output.log"

[server]
port = 8080

[jwt]
secret = "mySecret"
signatureAlgorithm = "HS512"
tokenValidityMinutes = 20
