[package]
name = "rust_actix"
version = "0.1.0"
authors = ["Francesco Cina <ufoscout@gmail.com>"]

[dependencies]
config = "0.9"
jsonwebtoken = "4.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
lazy_static = "1.0"
